### ISSUE TITLE
Mac version

### ISSUE THREAD

**Issue by SgtPooki** [cttynul/gimpshop-reloaded#1]
Is there anyone currently working on making an osx installable version? Is there a place other than github issues where you're tracking issues?

**Comment by cttynul** [comment]
I'vent got an OSX-Machine to test this, I've no idea where config folder are located, but I'm planning to make an installation tutorial as soon as I will have the possibility to use a Mac, if someone tried and succeeded installing this on OSX and wants to help us an how-to will be walcomed.

Issues are tracked only on github.

**Comment by rex4539** [comment]
This actually works fine on OSX without any tweaks.

Basically same manual installation as Linux. Just copy relevant files to ~/Library/Application\ Support/GIMP/2.X

That's it.

**Comment by cttynul** [comment]
@rex4539 so many thanks! Linked this post into readme and added you to "Thanks To" section, after a year, finally, this issue can be closed :).
