### ISSUE TITLE
Export dialog box focus/redraw issue on Mac OS using NEW CS6 theme for gimp

### ISSUE THREAD

**Issue by rex4539** [cttynul/gimpshop-reloaded#3]
Reproducibility: always

Pre-requisites:
"NEW CS6 theme for gimp" is selected.

Steps:
1. Open an image in GIMP.
2. File -> Export As
3. Try typing the filename on the "Name:" dialog box.

What happened:
There is a focus/redraw issue and text is not visible unless you double-click on the dialog.

https://www.dropbox.com/s/g3f8b8copublwtd/Gimpshop%20Reloaded%20Bug.mp4?dl=0

Expected result:
The dialog works normally.

**Comment by cttynul** [comment]
"Old" New CS6 Theme started being broken, it should be rewritten and **it will be done**, as you can see it's unusable on my system: https://raw.githubusercontent.com/cttynul/gimpshop-reloaded/gh-pages/img/fsafasf.png

Btw you can just use default "light" GIMP Theme and you won't lose any GIMPShop feature, except dark mode.

**Comment by rex4539** [comment]
This project appears to be abandoned. Retracting.

**Comment by cttynul** [comment]
as i can already say i've not a macos machine to test this.

remarked as "help wanted"
